version: "3.9"

services:
  node:
    build:
      context: .
    environment:
      - NODE_ENV=development
    command: yarn dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/opt/src
      - ./.env:/opt/.env
      - ./package.json:/opt/package.json
      - ./node_modules:/opt/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - ./database:/docker-entrypoint-initdb.d
